# Generated by Django 5.1.1 on 2024-09-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoalMine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('total_coal_extracted', models.FloatField(help_text='Total coal extracted in tonnes per year')),
                ('emission_factor', models.FloatField(help_text='Emission factor in tonnes CO2 per tonne of coal')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carbon_absorption_rate', models.FloatField(help_text='Carbon absorption rate in tonnes per year')),
            ],
        ),
    ]
