# Generated by Django 5.1 on 2024-08-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='shortdiscription',
            field=models.TextField(default='hello welcome the the software engineering job'),
            preserve_default=False,
        ),
    ]
