# Generated by Django 5.1 on 2024-08-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_shortdiscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='shortdiscription',
            new_name='shortdescription',
        ),
    ]
