# Generated by Django 5.0.8 on 2024-09-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevisit',
            old_name='paths',
            new_name='path',
        ),
    ]
