# Generated by Django 5.0.3 on 2024-08-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
