# Generated by Django 5.1 on 2024-08-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problem',
            new_name='Patient',
        ),
    ]
